### ISSUE TITLE
tab切换展示不同数据的场景，切换后图片会错乱 ——已解决，见详情

### ISSUE THREAD

**Issue by odayou** [Vitaminaq/vue-img-lazy-load#2]
更：自己的问题留着给发家警醒下
原因：tab切换时goods没有置空
////////////// 以下为原文
嗨,我在使用vue-img-lazy-load过程中无意间发现图片会错乱掉。
我的场景：在一个页面中有多个tab，点击某一个tab后请求接口加载相应的数据，展示在列表上，当浏览过第一个tab，点击第二个的时候会发现img标签产生的结果如下
# 产生的结构如下：
`<img data-v-05c6e514="" src="https://pic1.xxx.com/20191126/f99dc46090967e885a6953d20f0f9ca1_303x303M.png" data-lazy="https://pic.xxx.com/20191124/d117bc08342296c8f409bf4e64359d06_303x303M.jpg">`
其中data-lazy的内容是上一个tab时候的图片，这个时候虽然界面上看起来没问题，但是当滚动页面data-lazy的图片会展现出来

# 我的初始化
```
import VueImgLazyLoader from 'vue-images-lazy-load'
Vue.use(VueImgLazyLoader, {
  observerOptions: {
    rootMargin: '0px 0px 300px 0px',
    threshold: 0
  },
  delayTime: 0
})
```

# 我的调用（渲染图片部分）
```
<div class="goods" v-for="(item, index) in goods" :key="index">
        <div class="image">
            <img
              :src="item.goodsImgUrl[0]"
              v-img-lazy-load="{url: GLOBAL.lazyLoadImage}"
            />
          <div class="sale-tag" v-if="!item.goodsNum">抢光了</div>
        </div>
</div>
```

**Comment by Vitaminaq** [comment]
哈哈，厉害，欢迎提出优化建议，或者提交你的优化和想法
